AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  An example RESTful service

Resources:
  GetPythonChart:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: handler.main
      Events:
        GetChart:
          Type: Api
          Properties:
            Path: /
            Method: get  